services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.user
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=${MONGO_URI_USER}
    networks:
      - library-network
  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile.loan
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=${MONGO_URI_LOAN}
      - USER_SERVICE_URL=http://user-service:8081/api/users
      - BOOK_SERVICE_URL=http://book-service:8082/api/books
    depends_on:
      user-service:
        condition: service_started
      book-service:
        condition: service_started
    networks:
      - library-network
  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile.book
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=${MONGO_URI_BOOK}
    networks:
      - library-network
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - loan-service
      - book-service
    networks:
      - library-network
networks:
  library-network:
    driver: bridge